[chart.asa]
source        = imaps://chart.asa%40gmail.com:yheuxskizageiunm@imap.gmail.com:993
outgoing      = smtps://chart.asa%40gmail.com:yheuxskizageiunm@smtp.gmail.com:587
default       = INBOX
from          = Apichart Asavarojpanich <chart.asa@gmail.com>
cache-headers = true
[gm.clouddata]
source        = imaps://gm.clouddata%40gmail.com:phazvltlcgswlkjr@imap.gmail.com:993
outgoing      = smtps://gm.clouddata%40gmail.com:phazvltlcgswlkjr@smtp.gmail.com:587
default       = INBOX
from          = Apichart Asavarojpanich <gm.clouddata@gmail.com>
cache-headers = true
