require('chartasa.telescope')
require('chartasa.lf')
require('chartasa.nvim-web-devicons')
require('chartasa.bufferline-config')
require('chartasa.nvim-autopairs-config')
require('chartasa.nvim-tree-config')
require('chartasa.treesitter')
require('chartasa.whichkey')
require('chartasa.lightline')
require('chartasa.gitsigns')
require('chartasa.vimwiki')
require('chartasa.ultisnips')
-- for lsp config
require('chartasa.lspconfig')
--require('lsp.cmp')
--require('lsp.diagnostic_signs')
--require('lsp.language_servers')
