require('chartasa.telescope')
require('chartasa.lf')
require('chartasa.nvim-web-devicons')
require('chartasa.bufferline')
require('chartasa.nvim-autopairs-config')
require('chartasa.nvim-tree-config')
require('chartasa.treesitter')
require('chartasa.whichkey')
require('chartasa.lightline')
require('chartasa.gitsigns')
require('chartasa.vimwiki')
require('chartasa.toggleterm')
-- for snippets
require('chartasa.ultisnips')
require('chartasa.luasnip')
-- for lsp config
require('chartasa.lsp.lspconfig')
require('chartasa.lsp.handlers').setup()
require('chartasa.lsp.null-ls')
require('chartasa.lsp.lsp-signature')
require('chartasa.lsp.cmp')
--require('lsp.diagnostic_signs')
--require('lsp.language_servers')
